Add iconv detection for cross-platform build support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5160,7 +5160,80 @@ else
   LIB_THREADS=""
 fi
 
-
+# Check for iconv (in libc on Linux/glibc, separate libiconv on macOS)
+echo "$as_me:$LINENO: checking for iconv" >&5
+echo $ECHO_N "checking for iconv... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#include <iconv.h>
+int main() { iconv_open("", ""); return 0; }
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes (in libc)" >&5
+  echo "${ECHO_T}yes (in libc)" >&6
+  ICONV_LIBS=""
+else
+  echo "$as_me:$LINENO: result: no, checking for libiconv" >&5
+  echo "${ECHO_T}no, checking for libiconv" >&6
+  LIBS_save="$LIBS"
+  LIBS="$LIBS -liconv"
+  cat >conftest.$ac_ext <<_ACEOF
+#include <iconv.h>
+int main() { iconv_open("", ""); return 0; }
+_ACEOF
+  rm -f conftest.$ac_objext conftest$ac_exeext
+  if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+    (eval $ac_link) 2>conftest.er1
+    ac_status=$?
+    grep -v '^ *+' conftest.er1 >conftest.err
+    rm -f conftest.er1
+    cat conftest.err >&5
+    echo "$as_me:$LINENO: \$? = $ac_status" >&5
+    (exit $ac_status); } &&
+	   { ac_try='test -z "$ac_c_werror_flag"
+			   || test ! -s conftest.err'
+    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+    (eval $ac_try) 2>&5
+    ac_status=$?
+    echo "$as_me:$LINENO: \$? = $ac_status" >&5
+    (exit $ac_status); }; } &&
+	   { ac_try='test -s conftest$ac_exeext'
+    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+    (eval $ac_try) 2>&5
+    ac_status=$?
+    echo "$as_me:$LINENO: \$? = $ac_status" >&5
+    (exit $ac_status); }; }; then
+    echo "$as_me:$LINENO: result: yes (in libiconv)" >&5
+    echo "${ECHO_T}yes (in libiconv)" >&6
+    ICONV_LIBS="-liconv"
+  else
+    echo "$as_me:$LINENO: result: not found" >&5
+    echo "${ECHO_T}not found" >&6
+    ICONV_LIBS=""
+  fi
+  LIBS="$LIBS_save"
+fi
+rm -f conftest.err conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 
 
@@ -10223,6 +10296,7 @@ s,@ac_ct_CXX@,$ac_ct_CXX,;t t
 s,@PERL@,$PERL,;t t
 s,@CPP@,$CPP,;t t
 s,@LIB_THREADS@,$LIB_THREADS,;t t
+s,@ICONV_LIBS@,$ICONV_LIBS,;t t
 s,@ECHO@,$ECHO,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
